### ISSUE TITLE
Join table

### ISSUE THREAD

**Issue by Permagate** [dmfay/massive-js#263] opened 2016-06-03 00:17 UTC
I might be missing something obvious here, but is there a way to do a join table without having to run raw SQL?

I'd like to use the table API (find, findOne, etc2), but I'm not quite sure how to do that when I need to join the tables.

Thanks.

**Comment by dmfay** [comment] 2016-06-03 01:48
Massive's finders don't support looking at any relations other than the origin as yet, but as long as you have a standardized rather than an ad-hoc query you can put it in a view and use the finders on that just like you would a table.

**Comment by xivSolutions** [comment] 2016-06-03 02:54
There is not currently a way to do joins in Massive, but I personally think we may want to add that capability in v3. Up to @robconery ultimately. 

In the short-term, doing a SQL script and executing that per Massive's SQL-files-as-functions is the one way to do it, or per dmfay's comment, an ad-hoc query.

Note that part of the reasoning behind Massive is to encourage the use of SQL where it is more appropriate. Since Massive is not really an ORM in the typical sense, the notion of a join falls more into the SQL realm.

**Comment by Permagate** [comment] 2016-06-03 03:13
Ah, as I thought. Thanks for the answers :+1: 

Not that I'm adverse to using SQL, it's just feels weird seeing all these query API without having some ways to join the tables before executing the query. Association is such a common thing after all.

**Comment by dmfay** [comment] 2016-06-03 03:16
@xivSolutions a while back I built something to decompose results of a join query into an arbitrarily-deep nested structure. I haven't merged it in because it requires really clunky aliasing with double-underscores to separate path elements (`table1__table2__fieldname` etc) in the SQL script and hand-tuned definition for how to decompose the resultset in some cases, so it's not really in a publicly-releasable state imo.

It also needs Lodash, although I'm not 100% sure if I used anything not in Underscore (we might want to consider moving to that anyway, there's no reason to prefer the smaller library on the server side). But if there's interest in working out those other rough patches, that's one of the really complicated bits already done.

**Comment by quinn** [comment] 2016-11-14 03:20
@dmfay could you post what you have somewhere ? would love to take a look at it, building something very similar right now !

**Comment by dmfay** [comment] 2016-11-14 03:27
@quinn https://gist.github.com/dmfay/c4017b8768519679e7948706fc09532e

Thoroughly unofficial, you understand :)

**Comment by quinn** [comment] 2016-11-14 03:36
@dmfay yes, cool thanks :)

**Comment by brad-decker** [comment] 2017-07-28 18:05
@dmfay any update on when we might expect to see join capabilities?

**Comment by dmfay** [comment] 2017-07-28 18:13
It's a pretty long-term consideration for my part, although if someone wants to take it on I'd be happy to discuss how to fit it into the project.

**Comment by michaelzoidl** [comment] 2017-08-03 13:25
Another comfort solution - for now - is using the [sql-bricks](https://www.npmjs.com/package/sql-bricks) library to build those sql-statements, for example:
```js
db.run(select('field.team_id', 'team.title')
    .from('field')
    .join('team')
    .on({
      'field.team_id': 'team.id'
    })
    .where({
      'team.id': '52'
    })
    .toString())
```

For a solution in massive, has anyone a suggestion how the api should look? I tried to make a example, but it's quite hard to find a way to fit in the existing massive api.

**Comment by robconery** [comment] 2017-08-03 16:28
My feeling on this has always been to use SQL: it's the best DSL for working with the database. Given that Massive is PG-centric, there's no reason to hide SQL behind a weird abstraction that may or may not capture the nuance you're going for.

```sql
const sql = `select field.team_id, team.title
                     from field inner join team on team.id = field.team_id
                     where team_id=52`
return db.run(sql);
```

This is Dian's choice, of course. One reason you don't see joins in Massive is because I didn't create it to abstract SQL. I created it (among other reasons) to *help* when querying things, embracing SQL in PostgreSQL as a first class citizen.

**Comment by dmfay** [comment] 2017-08-03 22:07
Having given it a little more thought: this really isn't about providing a mechanism to emit `JOIN somethingelse ON somethingelse.x = something.y` as part of `db.something.find(...)`. That's a huge departure from what Massive does; like Rob said, it's abstracting SQL instead of facilitating it. The "Massive way", if that can be said to exist, is to turn those multi-table queries into views (or functions/scripts, if you need to apply parameters directly -- for example with pivots you want to restrict the number of rows as early as possible, so a view is unsuitable).

What I _am_ interested in with this feature is in making the results of multi-table queries immediately useful without manual post-processing. That's what the code in that gist does: given a row set, it decomposes it into an object tree based on matching named sub-rows. The problem is that in order to use it as written, you have to define those sub-rows in your select list, and that's... probably not the _worst_ feature I could come up with, but it's pretty bad.

Something that could work would be to skip the field name to schema translation from the gist implementation and pass the desired output schema in the `find` options. Given a table `parent` with a 1:many relationship to `children`, which in turn has a 1:1 relationship to `grandchildren`:

```
CREATE VIEW multitableview AS
SELECT
  parent.parentid, parent.parent1, parent.parent2,
  children.childid, children.child1, children.child2,
  grandchild.grandchildid, grandchild.grandchild1, grandchild.grandchild2
FROM parent
JOIN children ON children.parentid = parent.parentid
JOIN grandchildren ON grandchildren.childid = children.childid;
```

```
db.multitableview.find({}, {
  decompose: {
    pk: 'parentid',
    columns: ['parent1', 'parent2'],
    children: [{
      pk: 'childid',
      columns: ['child1', 'child2'],
      grandchild: [{
        pk: 'grandchildid',
        columns: ['grandchild1', 'grandchild2'],
        single: true
      }]
    }]
  }
}).then(...);
```

Sample output:

```
{
  parentid: 1,
  parent1: 'abc',
  parent2: 'def',
  children: [{
    childid: 11,
    child1: 'ghi',
    child2: 'jkl',
    grandchild: {
      grandchildid: 111,
      grandchild1: 'mno',
      grandchild2: 'pqr'
    }
  }]
}
```

My immediate critiques of this approach are:

* it assumes that nobody's going to want to do this with a field named `pk` or `columns`, or with a field named the same as a nested object/collection. This seems fair enough as long as it's documented.
* it's perhaps dangerously close to introducing models, and I don't like models at all :) That said, the decomposition schema is ad hoc and definitely easier than changing field names in a view, so I don't think that's worth worrying about.

I'm open to thoughts on this & alternate suggestions, if anyone has them!

**Closed** 2017-09-06 02:39 UTC
